### ISSUE TITLE
[추출/테이블] {tournament_id}_matches * N개 테이블 생성

### ISSUE THREAD

**Issue by haein-kim** [dataitgirls4/team_5#14]
*  url 에 플랫폼(shards/)을 steam 이 아니라 tournament 로 넣기  
예: `https://api.pubg.com/shards/tournaments/{match_id}`

- 총 N개의 tournament_id 👉 tournaments_list 참고
- tournament_id의 모든 match_id 내의 데이터들 (예: pcs3 (1) - match_id (24) - data (nn개))
- 최종 컬럼:
  **match_id | created_at | player_id | player_name | win_place | team_rank | stats * n | ...**

- [ ]  tournamets_list.csv에서 match_id와 created_at만 남기기
- [x]  matches에서 꺼낼 수 있는 정보 꺼내고 컬럼 추가
* name = player_id 주의 = GEN_Pio
- [x]  player_id에서 언더바 뒤만 스플릿해서 player_name 만들고 컬럼 추가

**Comment by heezeo** [comment]
matches 에서 꺼낼 수 있는 정보를 chicken_dinner 모듈의 처리 순서에 따라 3갈래로 분류하여 data frame 화 하였음. 그 과정은 이 [코드](https://github.com/dataitgirls4/team_5/blob/main/make_dataframe_from_json.py)에서 확인 가능. 

참고로 이 부분을 통해 shard 를 pc-tournament로 바꿔야 tournament 데이터에 접근 가능
`PUBG = PUBG(api_key=api_key, shard='pc-tournament', gzip=True)`
`PUBGCore = PUBGCore(api_key=api_key, shard='pc-tournament', gzip=True)`

### 조금 더 해야할 것

- [ ]  player_name 에서 팀 이름을 떼어내 player_id 칼럼으로 만드는 것 자동화 필요
- player_name 에서 팀 이름을 떼어내 팀 이름 칼럼으로 만들 필요가 있을 듯? <논의 필요>
- 데이터 프레임 나눈 방식에 대한 확실한 합의 필요. 뽑아내는 방식을 알았으므로 데이터 프레임화 하는 것에는 큰 어려움이 따르지 않을 것으로 보임 <논의 필요>
- telemetry를 효과적으로 관리하는 방법 <논의 및 연구 필요>

**Comment by kwiseon** [comment]
**player_name 에서 팀 이름을 떼어내 player_id 칼럼으로 만드는 것 자동화 필요**
for문 안에 넣는 것은 안되는데, 혹시 완성된 match_participant_stats 에서 잘라주는 것은 어떨까요? @heezeo 
저는 팀명, 선수명 칼럼으로 만들어두는 건 좋은 것 같습니다! 

```
match_participant_stats['team'] = match_participant.player_name.str.split('_').str[0]
match_participant_stats['player_name'] = match_participant.player_name.str.split('_').str[1]
match_participant_stats
```

![image](https://user-images.githubusercontent.com/70735494/99963683-79391480-2dd5-11eb-87bd-2e0ba2e53e6d.png)

**Comment by heezeo** [comment]
와우 그대로 반영 중!!! 아이디어 넘 감사해요 귀선님 🥰

**Comment by heezeo** [comment]
완전히 완료! 테이블 생성을 위한 for 문 완료하여 #30 DB 업로드 파일로 해당 내용 포함하여 진행할 예정~
