### ISSUE TITLE
[데이터 추출] e스포츠 선수 PCS3

### ISSUE THREAD

**Issue by haein-kim** [dataitgirls4/team_5#2]
목적: 토너먼트 별 선수 정보 활용을 위해서  
### 출발점
* ISSUE #1 : API 연결/respnse 200 까지 완료

### 작업 순서
데이터 가져오기 👉 데이터프레임으로 만들기 👉 csv로 저장하기

### 선수 ID 리스트 (2020.11)
>OGN_indigo
OGN_kAyle
OGN_Seongjang
OGN_Under

>AF_Hansia
AF_Shadow
AF_daengchae
AF_R0wha
AF_EJ

>GEN_Pio
GEN_Loki
GEN_Aqua5
GEN_Inonix

>GRF_Asura
GRF_2heart
GRF_2tap
GRF_Minsung
GRF_Hwan2da
GRF_Feint

>VRLU_Lambu
VRLU_Hikari
VRLU_DAEVA
VRLU_Spear
VRLU_PLIKHE

>OPGG_Ayoh
OPGG_Silky
OPGG_Dumbo
OPGG_Alphaca
OPGG_miha

### 저장할 데이터

**Comment by kwiseon** [comment]
**엔드포인트로 연결한 데이터, 데이터프레임으로 만들기**

이전에 불러온 데이터는 딕셔너리 형태로, 안에 또 다른 딕셔너리 데이터를 포함합니다. 이를 서브 딕셔너리라고 합니다. 
딕셔너리는 Key와 Value를 한 쌍으로 갖는 자료형이므로, key를 활용해 서브 딕셔너리를 출력, 데이터프레임을 만들었습니다. 
<br>

```
# 지난번에 출력한 데이터의 모양 
{'data': {'type': 'match',
  'id': 'ae1c96e4-8f39-4025-a926-ddf227045919',
  'attributes': {'duration': 1492,
   'stats': None,
   'gameMode': 'squad-fpp',
   'mapName': 'Baltic_Main',
   'isCustomMatch': False,
   'matchType': 'competitive',
   'createdAt': '2020-11-12T17:20:20Z',
   'titleId': 'bluehole-pubg',
   'shardId': 'steam',
   'tags': None,
   'seasonState': 'progress'}, .....
```
<br>

2tap 선수의 경기 데이터를 matches_GRF_2tap 이라고 부르겠습니다. 
```
print(matches_GRF_2tap.keys())
```
```
결과 : dict_keys(['data', 'included', 'links', 'meta'])
```


복잡해보이는 데이터 안에 key는 단 4개입니다. 하나씩 살펴본 결과 `data` 와 `included` 에 필요한 데이터가 있습니다. 
게임 플레이 정보가 담겨있는 included를 데이터프레임으로 만들어봅니다. 



```
matches_GRF_2tap = matches_GRF_2tap['included']
df1 = pd.DataFrame(matches_GRF_2tap)
df1
```

![image](https://user-images.githubusercontent.com/70735494/99276844-6f149480-2870-11eb-814b-70d8a52294a4.png)

attributes 안에 보고 싶은 경기 데이터가 들어있는 것 같습니다. 

다음에 진행할 것 
- attributes 열을 뽑아 따로 분석하기

**Comment by kwiseon** [comment]
**PUBG PLAYER RANKINGS**
https://ggscore.com/en/pubg/player?region=1&country=1

선수 ID 리스트 (2020.11)
> OGN_indigo
OGN_kAyle
OGN_Seongjang
OGN_Under

> AFF_Hansia
AFF_Shadow
AFF_daengchae
AFF_R0wha
AFF_EJ

> GEN_Pio
GEN_Loki
GEN_Aqua5
GEN_Inonix

> GRF_Asura
GRF_2heart
GRF_2tap
GRF_Minsung
GRF_Hwan2da
GRF_Feint

> VRLU_Lambu
VRLU_Hikari
VRLU_DAEVA
VRLU_Spear
VRLU_PLIKHE

> OPGG_Ayoh
OPGG_Silky
OPGG_Dumbo
OPGG_Alphaca
OPGG_miha

**Comment by haein-kim** [comment]
@kwiseon 귀선님!!! 죄송하지만ㅠㅠ 제가 이 이슈 내용을 바꿔버려가지고....
혹시
[데이터추출] response - JSON - 데이터프레임 하는 법

위 이름으로 이슈 새로 파고, 이 윗윗 코멘트 옮겨주실 수 있나요??
앞으로도 이거 관련된 얘기 그쪽에서 쭉 이어갈 수 있게!!

**Comment by haein-kim** [comment]
### pcs3 ASIA 매치 아이디 얻는 코드
```
import requests
import pandas as pd

api_key = "본인 API Key"

header = {
  "Authorization": api_key,
  "Accept": "application/vnd.api+json"
}

url = "https://api.pubg.com/tournaments/as-pcs3as"


r = requests.get(url, headers=header)
leagues_pcs3as = r.json()
leagues_pcs3as


matchId_dict = {match['attributes']['createdAt']: match['id'] for match in leagues_pcs3as['included']}
matchId_dict
matchId_df = pd.DataFrame(sorted(matchId_dict.items(), key=lambda x: x[0]), columns=['createdAt', 'matchId'])
matchId_df

matchId_df.to_csv("pcs3-matchId.csv")
```

**Comment by haein-kim** [comment]
**201117 정환님께 질문&답**  
Q. 토너먼트에서 as-pcs3as 넣어서 이번 매치들 아이디를 얻었는데, 매치스에 넣으니까 결과가 안나오네요ㅠㅠ 선수 개인이 플레이한 매치 아디이는 나오는데... 혹시 토너먼트는 다른 곳에서 찾아야 할까요?ㅠㅠ

A.
https://documentation.pubg.com/en/matches-endpoint.html  
요기에서 보시면 platform을 선택하는 부분이있어요  
```https://api.pubg.com/shards/tournament``` 요렇게 API 호출을 하셔야할거에요  
platform 부분이 tournament로 되어야해요!

**Comment by kwiseon** [comment]
**현재까지 pcs3 ASIA 매치 아이디(=경기 id)**
> 	createdAt	matchId
0	2020-11-05T10:23:44Z	d1532d6a-618b-49d1-b680-6535d82795c4 (우승 : Tian)
1	2020-11-05T11:12:43Z	023385f7-a73c-4cac-b86e-f550faf0c2ce (우승 : VLG)
2	2020-11-05T12:02:08Z	d43ea2dd-79c0-4967-ad7f-57fbe3dfbfed (우승 : ENT)
3	2020-11-05T12:49:20Z	4b2a265a-594e-40ae-8e1e-0e5e983e637f (우승 : AF)
4	2020-11-06T10:06:39Z	4a007b2f-7070-4f1f-9956-dfd17e6877ec (우승 : Tian)
5	2020-11-06T10:55:35Z	437d5fba-980f-46f0-90e8-9f7403fdb81c (우승 : 4AM)
6	2020-11-06T11:41:20Z	90a6d5ce-168e-4169-9ba6-680c3692f6f5 (우승 : 4AM)
7	2020-11-06T12:23:40Z	b74bdfcd-5916-45f6-8695-ce7c537eb558 (우승 : MCG)
8	2020-11-12T10:11:09Z	891e29a6-ad31-4ae6-9246-ea1582e554e4 (우승 : GEN)
9	2020-11-12T10:57:43Z	9053a89d-d488-40a6-af45-7215860bcacc (우승 : ENT)
10	2020-11-12T11:45:53Z	fec3964d-2e20-453f-8c41-5966aefa78d7 (우승 : AF)
11	2020-11-12T12:33:33Z	c17ca543-ef34-439c-8e79-bd3ead9075d5 (우승 : PeRO)
12	2020-11-13T10:06:35Z	d7a09b0b-3fa5-42b2-93de-c31c66f2ff30 (우승 : PeRO)
13	2020-11-13T10:53:23Z	e33b985e-1b52-4c87-8220-fb67562188ab (우승 : PeRO)
14	2020-11-13T11:46:01Z	07862b93-b175-4a9c-94de-a5460bd2de0a (우승 : Tian)
15	2020-11-13T12:37:12Z	b59c83ac-e7cf-4ebf-93fe-54d6ce8ca35c (우승 : OPGG)


**pcs3 ASIA 매치 아이디당 경기 결과 얻는 코드**
```
url = "https://api.pubg.com/shards/tournament/matches/d1532d6a-618b-49d1-b680-6535d82795c4"  

header = {
  "Authorization": "your ip",
  "Accept": "application/vnd.api+json"
}

m = requests.get(url, headers=header)
matches_pcs3_1 = m.json()
matches_pcs3_1
```
