### ISSUE TITLE
[DB] csv 파일을 MariaDB에 업로드

### ISSUE THREAD

**Issue by haein-kim** [dataitgirls4/team_5#22]
### 업로드 규칙
* 파일명 = 테이블명

### 업로드 할 파일 목록
* tournaments_list

**tournamets_matches**
* pcs3as_matches_info
* pcs3as_matches_participants_stats

**Comment by haein-kim** [comment]
### MariaDB 설치
* 윈도우 설치법 [여기](https://goddaehee.tistory.com/201)
* TCP 라는 거에서 충돌하면 [여기](https://velog.io/@haenyy3153/MariaDB-%EC%84%A4%EC%B9%98-%EC%8B%9C-TCP-Port-3306-%EC%A4%91%EB%B3%B5-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0) 참고
* HeidiSQL이라는 GUI 지원하는 툴이 같이 깔리는데, 이걸 사용할 예정

### 세션 로그인 관련

**Comment by kwiseon** [comment]
그럼 마리아 DB는 잠정 사용 중지일까요

**Comment by heezeo** [comment]
마리아 DB는 사용하지 않기로 했고, 멘토님께서 제공하시는 DB를 써보기로 했으니 이 이슈는 닫겠습니다! 고민해주신 해인님 감사합니다 🥰
