### ISSUE TITLE
[데이터추출] response - JSON - 데이터프레임 하는 법

### ISSUE THREAD

**Issue by kwiseon** [dataitgirls4/team_5#6]
**엔드포인트로 연결한 데이터, 데이터프레임으로 만들기**

이전에 불러온 데이터는 딕셔너리 형태로, 안에 또 다른 딕셔너리 데이터를 포함합니다. 이를 서브 딕셔너리라고 합니다. 
딕셔너리는 Key와 Value를 한 쌍으로 갖는 자료형이므로, key를 활용해 서브 딕셔너리를 출력, 데이터프레임을 만들었습니다. 
<br>

```
# 지난번에 출력한 데이터의 모양 
{'data': {'type': 'match',
  'id': 'ae1c96e4-8f39-4025-a926-ddf227045919',
  'attributes': {'duration': 1492,
   'stats': None,
   'gameMode': 'squad-fpp',
   'mapName': 'Baltic_Main',
   'isCustomMatch': False,
   'matchType': 'competitive',
   'createdAt': '2020-11-12T17:20:20Z',
   'titleId': 'bluehole-pubg',
   'shardId': 'steam',
   'tags': None,
   'seasonState': 'progress'}, .....
```
<br>

2tap 선수의 경기 데이터를 matches_GRF_2tap 이라고 부르겠습니다. 
```
print(matches_GRF_2tap.keys())
```
```
결과 : dict_keys(['data', 'included', 'links', 'meta'])
```

복잡해보이는 데이터 안에 key는 단 4개입니다. 하나씩 살펴본 결과 `data` 와 `included` 에 필요한 데이터가 있습니다. 
게임 플레이 정보가 담겨있는 included를 데이터프레임으로 만들어봅니다. 

```
matches_GRF_2tap = matches_GRF_2tap['included']
df1 = pd.DataFrame(matches_GRF_2tap)
df1
```

![image](https://user-images.githubusercontent.com/70735494/99276844-6f149480-2870-11eb-814b-70d8a52294a4.png)

attributes 안에 보고 싶은 경기 데이터가 들어있는 것 같습니다. 

다음에 진행할 것 
- attributes 열을 뽑아 따로 분석하기

**Comment by haein-kim** [comment]
### TOURNAMENT
(다른 사람 작업 참고한 건데, 공유해주신 거 보고 이것도 이해했습니다.)

```
leagues_pcs3as

matchId_dict = {match['attributes']['createdAt']: match['id'] for match in leagues_pcs3as['included']}
matchId_dict

pcs3_matchId_df = pd.DataFrame(sorted(matchId_dict.items(), key=lambda x: x[0]), columns=['createdAt', 'matchId'])

pcs3_matchId_df.to_csv("pcs3-matchId.csv")
```
